from typing import Any

from rdkit.AllChem import Mol

def CalcExactMolWt(mol: Mol, onlyHeavy: bool = ...) -> float: ...
def CalcMolFormula(
    mol: Mol, separateIsotopes: bool = ..., abbreviateHIsotopes: bool = ...
) -> str: ...
def __getattr__(name: str) -> Any: ...
