# Generated by Django 4.1.1 on 2022-10-03 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_rdkit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('molecule', django_rdkit.models.fields.MolField()),
                ('molecular_formula', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='molecules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReactionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reaction_sources', to=settings.AUTH_USER_MODEL)),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_sources', to='road.reaction')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('reactant', 'Reactant'), ('product', 'Product'), ('agent', 'Agent')], max_length=10)),
                ('count_numerator', models.IntegerField(default=1)),
                ('count_denominator', models.IntegerField(default=1)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='components', to='road.molecule')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='components', to=settings.AUTH_USER_MODEL)),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='road.reaction')),
            ],
        ),
    ]
