# Generated by Django 4.1.1 on 2022-12-31 04:02

from django.db import migrations
import road.models


class Migration(migrations.Migration):

    dependencies = [
        ("road", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="molecule",
            name="molecule",
            field=road.models.SerializableMolField(),
        ),
    ]
