# Generated by Django 4.1.1 on 2023-01-18 06:26

from django.db import migrations
import road.models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0002_alter_molecule_molecule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='molecule',
            field=road.models.SerializableMolField(unique=True),
        ),
    ]
